import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navigation from '../components/navbar'
import Jumbotron from './home'
import Content from './content'
import Footer from '../components/footer'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logopmk.png" />
      </Head>
    <Navigation/>
    <Jumbotron/>
    <Content/>
    <Footer/>
    
      
    </div>
  )
}
